# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.publisher import Publisher  # noqa: E501
from swagger_client.rest import ApiException


class TestPublisher(unittest.TestCase):
    """Publisher unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublisher(self):
        """Test Publisher"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.publisher.Publisher()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
