# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ad_source_adapter_api import AdSourceAdapterApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdSourceAdapterApi(unittest.TestCase):
    """AdSourceAdapterApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.ad_source_adapter_api.AdSourceAdapterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pop(self):
        """Test case for pop

        AdSourceAdapterResource - pop  # noqa: E501
        """
        pass

    def test_produce_ad(self):
        """Test case for produce_ad

        AdSourceAdapterResource - produceAd  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
