# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.impression_info import ImpressionInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestImpressionInfo(unittest.TestCase):
    """ImpressionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImpressionInfo(self):
        """Test ImpressionInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.impression_info.ImpressionInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
