# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ad_request_vector import AdRequestVector  # noqa: E501
from swagger_client.rest import ApiException


class TestAdRequestVector(unittest.TestCase):
    """AdRequestVector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdRequestVector(self):
        """Test AdRequestVector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ad_request_vector.AdRequestVector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
