# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.impressions_validation_data import ImpressionsValidationData  # noqa: E501
from swagger_client.rest import ApiException


class TestImpressionsValidationData(unittest.TestCase):
    """ImpressionsValidationData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImpressionsValidationData(self):
        """Test ImpressionsValidationData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.impressions_validation_data.ImpressionsValidationData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
