# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ad_source_api import AdSourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdSourceApi(unittest.TestCase):
    """AdSourceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.ad_source_api.AdSourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bulk_resolve_source(self):
        """Test case for bulk_resolve_source

        AdSourceResource - bulkResolveSources  # noqa: E501
        """
        pass

    def test_delete_source(self):
        """Test case for delete_source

        AdSourceResource - deleteSource  # noqa: E501
        """
        pass

    def test_get_all_authorized_sources(self):
        """Test case for get_all_authorized_sources

        AdSourceResource - getAllAuthorizedSources  # noqa: E501
        """
        pass

    def test_register_source(self):
        """Test case for register_source

        AdSourceResource - registerSource  # noqa: E501
        """
        pass

    def test_update_source(self):
        """Test case for update_source

        AdSourceResource - updateSource  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
