# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.monetary_requirement_info import MonetaryRequirementInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestMonetaryRequirementInfo(unittest.TestCase):
    """MonetaryRequirementInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonetaryRequirementInfo(self):
        """Test MonetaryRequirementInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.monetary_requirement_info.MonetaryRequirementInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
