# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.aot_file import AotFile  # noqa: E501
from swagger_client.rest import ApiException


class TestAotFile(unittest.TestCase):
    """AotFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAotFile(self):
        """Test AotFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.aot_file.AotFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
