# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.delivery_api import DeliveryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeliveryApi(unittest.TestCase):
    """DeliveryApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.delivery_api.DeliveryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_next_ad(self):
        """Test case for get_next_ad

        Get next Ad  # noqa: E501
        """
        pass

    def test_pop_ad(self):
        """Test case for pop_ad

        Trigger Proof of Play on Ad  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
