# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_token_api import APITokenApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPITokenApi(unittest.TestCase):
    """APITokenApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.api_token_api.APITokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_account(self):
        """Test case for create_account

        Creates an Ads on Top Dynamix account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
