# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_source_content_api import DefaultSourceContentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultSourceContentApi(unittest.TestCase):
    """DefaultSourceContentApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_source_content_api.DefaultSourceContentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_content(self):
        """Test case for delete_content

        DefaultSourceContentResource - deleteContent  # noqa: E501
        """
        pass

    def test_get_all_authorized_content_paged(self):
        """Test case for get_all_authorized_content_paged

        """
        pass

    def test_get_content_request(self):
        """Test case for get_content_request

        """
        pass

    def test_register_new_content(self):
        """Test case for register_new_content

        DefaultSourceContentResource - registerNewContent  # noqa: E501
        """
        pass

    def test_update_content(self):
        """Test case for update_content

        DefaultSourceContentResource - updateContent  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        DefaultSourceContentResource - uploadFile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
