# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.day_bounded_time_range import DayBoundedTimeRange  # noqa: E501
from swagger_client.rest import ApiException


class TestDayBoundedTimeRange(unittest.TestCase):
    """DayBoundedTimeRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDayBoundedTimeRange(self):
        """Test DayBoundedTimeRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.day_bounded_time_range.DayBoundedTimeRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
