# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.publisher_api import PublisherApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPublisherApi(unittest.TestCase):
    """PublisherApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.publisher_api.PublisherApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bulk_resolve_publishers(self):
        """Test case for bulk_resolve_publishers

        PublisherResource - bulkResolvePublishers  # noqa: E501
        """
        pass

    def test_delete_publisher(self):
        """Test case for delete_publisher

        PublisherResource - deletePublisher  # noqa: E501
        """
        pass

    def test_get_all_authorized_publishers(self):
        """Test case for get_all_authorized_publishers

        PublisherResource - getAllAuthorizedPublishers  # noqa: E501
        """
        pass

    def test_register_publisher(self):
        """Test case for register_publisher

        PublisherResource - registerPublisher  # noqa: E501
        """
        pass

    def test_update_publisher(self):
        """Test case for update_publisher

        PublisherResource - updatePublisher  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
