# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AdMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'slot_length_in_milliseconds': 'int',
        'cachable': 'bool'
    }

    attribute_map = {
        'slot_length_in_milliseconds': 'slotLengthInMilliseconds',
        'cachable': 'cachable'
    }

    def __init__(self, slot_length_in_milliseconds=None, cachable=None):  # noqa: E501
        """AdMetadata - a model defined in Swagger"""  # noqa: E501

        self._slot_length_in_milliseconds = None
        self._cachable = None
        self.discriminator = None

        if slot_length_in_milliseconds is not None:
            self.slot_length_in_milliseconds = slot_length_in_milliseconds
        if cachable is not None:
            self.cachable = cachable

    @property
    def slot_length_in_milliseconds(self):
        """Gets the slot_length_in_milliseconds of this AdMetadata.  # noqa: E501


        :return: The slot_length_in_milliseconds of this AdMetadata.  # noqa: E501
        :rtype: int
        """
        return self._slot_length_in_milliseconds

    @slot_length_in_milliseconds.setter
    def slot_length_in_milliseconds(self, slot_length_in_milliseconds):
        """Sets the slot_length_in_milliseconds of this AdMetadata.


        :param slot_length_in_milliseconds: The slot_length_in_milliseconds of this AdMetadata.  # noqa: E501
        :type: int
        """

        self._slot_length_in_milliseconds = slot_length_in_milliseconds

    @property
    def cachable(self):
        """Gets the cachable of this AdMetadata.  # noqa: E501


        :return: The cachable of this AdMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._cachable

    @cachable.setter
    def cachable(self, cachable):
        """Sets the cachable of this AdMetadata.


        :param cachable: The cachable of this AdMetadata.  # noqa: E501
        :type: bool
        """

        self._cachable = cachable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
