# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AdSourceRestriction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ad_source_rids': 'list[str]'
    }

    attribute_map = {
        'ad_source_rids': 'adSourceRids'
    }

    def __init__(self, ad_source_rids=None):  # noqa: E501
        """AdSourceRestriction - a model defined in Swagger"""  # noqa: E501

        self._ad_source_rids = None
        self.discriminator = None

        if ad_source_rids is not None:
            self.ad_source_rids = ad_source_rids

    @property
    def ad_source_rids(self):
        """Gets the ad_source_rids of this AdSourceRestriction.  # noqa: E501


        :return: The ad_source_rids of this AdSourceRestriction.  # noqa: E501
        :rtype: list[str]
        """
        return self._ad_source_rids

    @ad_source_rids.setter
    def ad_source_rids(self, ad_source_rids):
        """Sets the ad_source_rids of this AdSourceRestriction.


        :param ad_source_rids: The ad_source_rids of this AdSourceRestriction.  # noqa: E501
        :type: list[str]
        """

        self._ad_source_rids = ad_source_rids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdSourceRestriction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
