# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.file_metadata import FileMetadata  # noqa: F401,E501


class AotFile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_location': 'str',
        'file_metadata': 'FileMetadata'
    }

    attribute_map = {
        'file_location': 'fileLocation',
        'file_metadata': 'fileMetadata'
    }

    def __init__(self, file_location=None, file_metadata=None):  # noqa: E501
        """AotFile - a model defined in Swagger"""  # noqa: E501

        self._file_location = None
        self._file_metadata = None
        self.discriminator = None

        if file_location is not None:
            self.file_location = file_location
        if file_metadata is not None:
            self.file_metadata = file_metadata

    @property
    def file_location(self):
        """Gets the file_location of this AotFile.  # noqa: E501


        :return: The file_location of this AotFile.  # noqa: E501
        :rtype: str
        """
        return self._file_location

    @file_location.setter
    def file_location(self, file_location):
        """Sets the file_location of this AotFile.


        :param file_location: The file_location of this AotFile.  # noqa: E501
        :type: str
        """

        self._file_location = file_location

    @property
    def file_metadata(self):
        """Gets the file_metadata of this AotFile.  # noqa: E501


        :return: The file_metadata of this AotFile.  # noqa: E501
        :rtype: FileMetadata
        """
        return self._file_metadata

    @file_metadata.setter
    def file_metadata(self, file_metadata):
        """Sets the file_metadata of this AotFile.


        :param file_metadata: The file_metadata of this AotFile.  # noqa: E501
        :type: FileMetadata
        """

        self._file_metadata = file_metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AotFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
