# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ImpressionInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'impressions_available': 'int'
    }

    attribute_map = {
        'impressions_available': 'impressionsAvailable'
    }

    def __init__(self, impressions_available=None):  # noqa: E501
        """ImpressionInfo - a model defined in Swagger"""  # noqa: E501

        self._impressions_available = None
        self.discriminator = None

        self.impressions_available = impressions_available

    @property
    def impressions_available(self):
        """Gets the impressions_available of this ImpressionInfo.  # noqa: E501


        :return: The impressions_available of this ImpressionInfo.  # noqa: E501
        :rtype: int
        """
        return self._impressions_available

    @impressions_available.setter
    def impressions_available(self, impressions_available):
        """Sets the impressions_available of this ImpressionInfo.


        :param impressions_available: The impressions_available of this ImpressionInfo.  # noqa: E501
        :type: int
        """
        if impressions_available is None:
            raise ValueError("Invalid value for `impressions_available`, must not be `None`")  # noqa: E501

        self._impressions_available = impressions_available

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImpressionInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
