# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.address import Address  # noqa: F401,E501
from swagger_client.models.demographic_vector import DemographicVector  # noqa: F401,E501


class PublisherLocationInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'latitude': 'float',
        'longitude': 'float',
        'address': 'Address',
        'demographic_vector': 'DemographicVector'
    }

    attribute_map = {
        'latitude': 'latitude',
        'longitude': 'longitude',
        'address': 'address',
        'demographic_vector': 'demographicVector'
    }

    def __init__(self, latitude=None, longitude=None, address=None, demographic_vector=None):  # noqa: E501
        """PublisherLocationInfo - a model defined in Swagger"""  # noqa: E501

        self._latitude = None
        self._longitude = None
        self._address = None
        self._demographic_vector = None
        self.discriminator = None

        self.latitude = latitude
        self.longitude = longitude
        if address is not None:
            self.address = address
        if demographic_vector is not None:
            self.demographic_vector = demographic_vector

    @property
    def latitude(self):
        """Gets the latitude of this PublisherLocationInfo.  # noqa: E501


        :return: The latitude of this PublisherLocationInfo.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this PublisherLocationInfo.


        :param latitude: The latitude of this PublisherLocationInfo.  # noqa: E501
        :type: float
        """
        if latitude is None:
            raise ValueError("Invalid value for `latitude`, must not be `None`")  # noqa: E501

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this PublisherLocationInfo.  # noqa: E501


        :return: The longitude of this PublisherLocationInfo.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this PublisherLocationInfo.


        :param longitude: The longitude of this PublisherLocationInfo.  # noqa: E501
        :type: float
        """
        if longitude is None:
            raise ValueError("Invalid value for `longitude`, must not be `None`")  # noqa: E501

        self._longitude = longitude

    @property
    def address(self):
        """Gets the address of this PublisherLocationInfo.  # noqa: E501


        :return: The address of this PublisherLocationInfo.  # noqa: E501
        :rtype: Address
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this PublisherLocationInfo.


        :param address: The address of this PublisherLocationInfo.  # noqa: E501
        :type: Address
        """

        self._address = address

    @property
    def demographic_vector(self):
        """Gets the demographic_vector of this PublisherLocationInfo.  # noqa: E501


        :return: The demographic_vector of this PublisherLocationInfo.  # noqa: E501
        :rtype: DemographicVector
        """
        return self._demographic_vector

    @demographic_vector.setter
    def demographic_vector(self, demographic_vector):
        """Sets the demographic_vector of this PublisherLocationInfo.


        :param demographic_vector: The demographic_vector of this PublisherLocationInfo.  # noqa: E501
        :type: DemographicVector
        """

        self._demographic_vector = demographic_vector

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PublisherLocationInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
