# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ResourceIdentifier(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service': 'str',
        'instance': 'str',
        'type': 'str',
        'locator': 'str'
    }

    attribute_map = {
        'service': 'service',
        'instance': 'instance',
        'type': 'type',
        'locator': 'locator'
    }

    def __init__(self, service=None, instance=None, type=None, locator=None):  # noqa: E501
        """ResourceIdentifier - a model defined in Swagger"""  # noqa: E501

        self._service = None
        self._instance = None
        self._type = None
        self._locator = None
        self.discriminator = None

        if service is not None:
            self.service = service
        if instance is not None:
            self.instance = instance
        if type is not None:
            self.type = type
        if locator is not None:
            self.locator = locator

    @property
    def service(self):
        """Gets the service of this ResourceIdentifier.  # noqa: E501


        :return: The service of this ResourceIdentifier.  # noqa: E501
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this ResourceIdentifier.


        :param service: The service of this ResourceIdentifier.  # noqa: E501
        :type: str
        """

        self._service = service

    @property
    def instance(self):
        """Gets the instance of this ResourceIdentifier.  # noqa: E501


        :return: The instance of this ResourceIdentifier.  # noqa: E501
        :rtype: str
        """
        return self._instance

    @instance.setter
    def instance(self, instance):
        """Sets the instance of this ResourceIdentifier.


        :param instance: The instance of this ResourceIdentifier.  # noqa: E501
        :type: str
        """

        self._instance = instance

    @property
    def type(self):
        """Gets the type of this ResourceIdentifier.  # noqa: E501


        :return: The type of this ResourceIdentifier.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ResourceIdentifier.


        :param type: The type of this ResourceIdentifier.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def locator(self):
        """Gets the locator of this ResourceIdentifier.  # noqa: E501


        :return: The locator of this ResourceIdentifier.  # noqa: E501
        :rtype: str
        """
        return self._locator

    @locator.setter
    def locator(self, locator):
        """Sets the locator of this ResourceIdentifier.


        :param locator: The locator of this ResourceIdentifier.  # noqa: E501
        :type: str
        """

        self._locator = locator

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceIdentifier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
