# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ScreenDimensions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'height_in_meters': 'float',
        'width_in_meters': 'float'
    }

    attribute_map = {
        'height_in_meters': 'heightInMeters',
        'width_in_meters': 'widthInMeters'
    }

    def __init__(self, height_in_meters=None, width_in_meters=None):  # noqa: E501
        """ScreenDimensions - a model defined in Swagger"""  # noqa: E501

        self._height_in_meters = None
        self._width_in_meters = None
        self.discriminator = None

        self.height_in_meters = height_in_meters
        self.width_in_meters = width_in_meters

    @property
    def height_in_meters(self):
        """Gets the height_in_meters of this ScreenDimensions.  # noqa: E501


        :return: The height_in_meters of this ScreenDimensions.  # noqa: E501
        :rtype: float
        """
        return self._height_in_meters

    @height_in_meters.setter
    def height_in_meters(self, height_in_meters):
        """Sets the height_in_meters of this ScreenDimensions.


        :param height_in_meters: The height_in_meters of this ScreenDimensions.  # noqa: E501
        :type: float
        """
        if height_in_meters is None:
            raise ValueError("Invalid value for `height_in_meters`, must not be `None`")  # noqa: E501

        self._height_in_meters = height_in_meters

    @property
    def width_in_meters(self):
        """Gets the width_in_meters of this ScreenDimensions.  # noqa: E501


        :return: The width_in_meters of this ScreenDimensions.  # noqa: E501
        :rtype: float
        """
        return self._width_in_meters

    @width_in_meters.setter
    def width_in_meters(self, width_in_meters):
        """Sets the width_in_meters of this ScreenDimensions.


        :param width_in_meters: The width_in_meters of this ScreenDimensions.  # noqa: E501
        :type: float
        """
        if width_in_meters is None:
            raise ValueError("Invalid value for `width_in_meters`, must not be `None`")  # noqa: E501

        self._width_in_meters = width_in_meters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScreenDimensions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
