# coding: utf-8

"""
    Dynamix

    Sign up for Dynamix & grab your token.  # noqa: E501

    OpenAPI spec version: v0.1.0
    Contact: david@theadsontop.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TimeRange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_hour': 'int',
        'start_minute': 'int',
        'end_hour': 'int',
        'end_minute': 'int'
    }

    attribute_map = {
        'start_hour': 'startHour',
        'start_minute': 'startMinute',
        'end_hour': 'endHour',
        'end_minute': 'endMinute'
    }

    def __init__(self, start_hour=None, start_minute=None, end_hour=None, end_minute=None):  # noqa: E501
        """TimeRange - a model defined in Swagger"""  # noqa: E501

        self._start_hour = None
        self._start_minute = None
        self._end_hour = None
        self._end_minute = None
        self.discriminator = None

        if start_hour is not None:
            self.start_hour = start_hour
        if start_minute is not None:
            self.start_minute = start_minute
        if end_hour is not None:
            self.end_hour = end_hour
        if end_minute is not None:
            self.end_minute = end_minute

    @property
    def start_hour(self):
        """Gets the start_hour of this TimeRange.  # noqa: E501


        :return: The start_hour of this TimeRange.  # noqa: E501
        :rtype: int
        """
        return self._start_hour

    @start_hour.setter
    def start_hour(self, start_hour):
        """Sets the start_hour of this TimeRange.


        :param start_hour: The start_hour of this TimeRange.  # noqa: E501
        :type: int
        """

        self._start_hour = start_hour

    @property
    def start_minute(self):
        """Gets the start_minute of this TimeRange.  # noqa: E501


        :return: The start_minute of this TimeRange.  # noqa: E501
        :rtype: int
        """
        return self._start_minute

    @start_minute.setter
    def start_minute(self, start_minute):
        """Sets the start_minute of this TimeRange.


        :param start_minute: The start_minute of this TimeRange.  # noqa: E501
        :type: int
        """

        self._start_minute = start_minute

    @property
    def end_hour(self):
        """Gets the end_hour of this TimeRange.  # noqa: E501


        :return: The end_hour of this TimeRange.  # noqa: E501
        :rtype: int
        """
        return self._end_hour

    @end_hour.setter
    def end_hour(self, end_hour):
        """Sets the end_hour of this TimeRange.


        :param end_hour: The end_hour of this TimeRange.  # noqa: E501
        :type: int
        """

        self._end_hour = end_hour

    @property
    def end_minute(self):
        """Gets the end_minute of this TimeRange.  # noqa: E501


        :return: The end_minute of this TimeRange.  # noqa: E501
        :rtype: int
        """
        return self._end_minute

    @end_minute.setter
    def end_minute(self, end_minute):
        """Sets the end_minute of this TimeRange.


        :param end_minute: The end_minute of this TimeRange.  # noqa: E501
        :type: int
        """

        self._end_minute = end_minute

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimeRange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
